### ISSUE TITLE
Review the README

### ISSUE THREAD

**Issue by quantumm** [Democratie-Libre/democratie-libre#15]

**Comment by Einenlum** [comment]
- Readme:
    - Cloner le dépot
    - sudo setfacl -R -m u:www-data:rwx -m u:`whoami`:rwx app/cache app/logs // plus à jour
    - mkdir -p var
    - Pour tester web/config.php, d’abord démarrer serveur
    - In principle a PHP version 5.4.11 or above is needed. // ça dégage
    - bin/install ?
    - app/console doctrine… // ça dégage
    - ./bin/console doc:data:drop --force --if-exists

    - requirements:
        - mysql
        - pdo-mysql 

- composer.json
    - pdo-mysql
